import type { Metadata } from "next";
import { Roboto, Roboto_Mono, Libre_Baskerville } from "next/font/google";
import "./globals.css";
import { Layout } from "@/components/common/Layout/Layout";

const robotoSans = Roboto({
    subsets: ["latin"],
    variable: "--font-roboto-sans",
    weight: ["200", "400"],
    // ensures that text remains visible during font loading, preventing a "flash of invisible text" (FOIT).
    display: "swap"
});

const robotoMono = Roboto_Mono({
    subsets: ["latin"],
    variable: "--font-roboto-mono",
    weight: ["200", "400"],
    // ensures that text remains visible during font loading, preventing a "flash of invisible text" (FOIT).
    display: "swap"
});

const libre_baskerville = Libre_Baskerville({
    subsets: ["latin"],
    weight: ["400"],
    variable: "--font-libre-baskerville",
    // ensures that text remains visible during font loading, preventing a "flash of invisible text" (FOIT).
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${robotoSans.variable} ${robotoMono.variable} ${libre_baskerville.variable} antialiased`}
            >
                <Layout>
                    {children}
                </Layout>
            </body>
        </html>
    );
}
