import type { Metadata } from "next";
import { Roboto, Roboto_Mono, Libre_Baskerville } from "next/font/google";
import { Layout } from "@/components/common/Layout/Layout";
import { ThemeProvider } from "@/components/common/Layout/ThemeProvider";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query"
import "./globals.css";

const robotoSans = Roboto({
    subsets: ["latin"],
    variable: "--font-roboto-sans",
    weight: ["200", "400"],
    // ensures that text remains visible during font loading, preventing a "flash of invisible text" (FOIT).
    display: "swap"
});

const robotoMono = Roboto_Mono({
    subsets: ["latin"],
    variable: "--font-roboto-mono",
    weight: ["200", "400"],
    // ensures that text remains visible during font loading, preventing a "flash of invisible text" (FOIT).
    display: "swap"
});

const libre_baskerville = Libre_Baskerville({
    subsets: ["latin"],
    weight: ["400"],
    variable: "--font-libre-baskerville",
    // ensures that text remains visible during font loading, preventing a "flash of invisible text" (FOIT).
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

// Create query client for tanstack
const queryClient = new QueryClient();

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${robotoSans.variable} ${robotoMono.variable} ${libre_baskerville.variable} antialiased`}
            >
                <QueryClientProvider client={queryClient}>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <Layout>
                            {children}
                        </Layout>
                    </ThemeProvider>
                </QueryClientProvider>
            </body>
        </html>
    );
}
